#!/bin/bash

set -o nounset
set -o errexit

WORKDIR='/opt'
PIDFILE='/var/run/celerybeat.pid'

trap "rm ${PIDFILE} ; exit 130" SIGINT
trap "rm ${PIDFILE} ; exit 137" SIGKILL
trap "rm ${PIDFILE} ; exit 143" SIGTERM

# Should we be doing this this way?
# What should we do to cleanup in a container?
if [[ -f $PIDFILE ]]
then
  rm $PIDFILE
fi

cd $WORKDIR
exec celery beat --app=mhn.tasks \
                 --pidfile=${PIDFILE} \
                 --loglevel=INFO
