FROM centos:centos7

LABEL maintainer Chris Collins <collins.christopher@gmail.com>
LABEL name "chn-server"
LABEL version "0.1"
LABEL release "1"
LABEL summary "Community Honey Network Server"
LABEL description "Multi-snort and honeypot sensor management, uses a network of VMs, small footprint SNORT installations, stealthy dionaeas, and a centralized server for management."
LABEL authoritative-source-url "https://github.com/CommunityHoneyNetwork/communityhoneynetwork"
LABEL changelog-url "https://github.com/CommunityHoneyNetwork/communityhoneynetwork/commits/master"

ENV playbook "chnserver.yml"

RUN yum install -y epel-release \
      && yum install -y ansible

RUN echo "localhost ansible_connection=local" >> /etc/ansible/hosts
ADD . /opt/
RUN ansible-playbook /opt/${playbook}

ENTRYPOINT ["/sbin/runsvdir", "-P", "/etc/service"]

